import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { z } from "zod";
import { upsertRecords, pullSince } from "./db.js";

// ── Schemas ───────────────────────────────────────────────────────────────────

const RecordSchema = z.object({
  id: z.string().min(1),
  type: z.string().min(1),
  body: z.union([z.string(), z.record(z.unknown())]),
  created_at: z.number().int(),
  updated_at: z.number().int(),
  deleted: z.boolean().default(false),
});

const SyncBodySchema = z.object({
  /** Reverse-DNS app identifier from the manifest, e.g. `com.example.myapp` */
  appId: z.string().min(1),
  /** Stable per-device UUID generated by the viewer on first sync */
  deviceId: z.string().min(1),
  /** Epoch ms of the last successful sync; 0 = full pull */
  lastSync: z.number().int().min(0).default(0),
  /** Records the client wants to push (may be empty) */
  push: z.array(RecordSchema).default([]),
});

// ── Router ────────────────────────────────────────────────────────────────────

export const syncRouter = new Hono();

/**
 * POST /sync
 *
 * Single endpoint for push + pull in one round-trip.
 *
 * Flow:
 *  1. Upsert all `push` records using last-write-wins on `updated_at`.
 *  2. Return all server records with `updated_at > lastSync` as `pull`.
 *     (This may include records the client just pushed if the server kept a
 *      different — newer — version; clients should apply them.)
 *  3. Return the server's wall clock as `serverTime`; client stores this as
 *     the new `lastSync` for the next call.
 */
syncRouter.post("/", zValidator("json", SyncBodySchema), (c) => {
  const { appId, lastSync, push } = c.req.valid("json");
  const serverTime = Date.now();

  const pushed = upsertRecords(
    appId,
    push as Parameters<typeof upsertRecords>[1],
  );
  const pull = pullSince(appId, lastSync);

  return c.json({ pull, pushed, serverTime });
});
